package cn.bugstack.ai.infrastructure.persistence.sqlite;

import cn.bugstack.ai.domain.agent.memory.adapter.repository.IMemoryRepository;
import cn.bugstack.ai.domain.agent.memory.model.entity.AgentMemoryEntity;
import cn.bugstack.ai.domain.agent.memory.model.entity.MemoryEvidenceEntity;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
import org.springframework.stereotype.Repository;

import java.nio.file.Path;
import java.sql.*;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

@Repository
@ConditionalOnProperty(name="ai.agent.persistence.mode", havingValue="file")
public class SqliteMemoryRepository implements IMemoryRepository {
    private final String url;
    public SqliteMemoryRepository(@Value("${ai.agent.persistence.root:${user.dir}/data/agent-runtime}")String root){url="jdbc:sqlite:"+Path.of(root).toAbsolutePath().normalize().resolve("agent-platform.db");}
    private Connection c()throws SQLException{Connection c=DriverManager.getConnection(url);try(Statement s=c.createStatement()){s.execute("PRAGMA busy_timeout=5000");}return c;}
    @Override public AgentMemoryEntity insert(AgentMemoryEntity m){try(Connection c=c()){c.setAutoCommit(false);try(PreparedStatement p=c.prepareStatement("INSERT INTO agent_memory VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)")){bind(p,m);p.executeUpdate();}if(m.getSourceSessionId()!=null&&!m.getSourceSessionId().isBlank())evidence(c,m.getMemoryId(),"SESSION",m.getSourceSessionId(),m.getCreatedAt());if(m.getSourceEventId()!=null&&!m.getSourceEventId().isBlank())evidence(c,m.getMemoryId(),"EVENT",m.getSourceEventId(),m.getCreatedAt());c.commit();return m;}catch(SQLException e){throw new IllegalStateException(e);}}
    @Override public Optional<AgentMemoryEntity> findById(String id){try(Connection c=c();PreparedStatement p=c.prepareStatement("SELECT * FROM agent_memory WHERE memory_id=? AND deleted=0")){p.setString(1,id);try(ResultSet r=p.executeQuery()){return r.next()?Optional.of(map(r)):Optional.empty();}}catch(SQLException e){throw new IllegalStateException(e);}}
    @Override public List<AgentMemoryEntity> find(String user,String project,String type,int limit){String sql="SELECT * FROM agent_memory WHERE user_id=? AND deleted=0 AND (? IS NULL OR project_id=?) AND (? IS NULL OR memory_type=?) ORDER BY confirmed DESC,importance DESC,updated_at DESC LIMIT ?";return query(sql,p->{p.setString(1,user);p.setString(2,project);p.setString(3,project);p.setString(4,type);p.setString(5,type);p.setInt(6,limit);});}
    @Override public List<AgentMemoryEntity> search(String user,String project,String text,int limit){if(text!=null&&!text.isBlank()){String match=ftsQuery(text);String sql="SELECT m.* FROM agent_memory_fts f JOIN agent_memory m ON m.memory_id=f.memory_id WHERE f.agent_memory_fts MATCH ? AND m.user_id=? AND m.deleted=0 AND (m.project_id IS NULL OR m.project_id=?) AND (m.expires_at IS NULL OR m.expires_at>?) ORDER BY m.confirmed DESC,m.importance DESC,m.confidence DESC,m.updated_at DESC LIMIT ?";List<AgentMemoryEntity> hits=query(sql,p->{p.setString(1,match);p.setString(2,user);p.setString(3,project);p.setLong(4,System.currentTimeMillis());p.setInt(5,limit);});if(!hits.isEmpty())return hits;}String q="%"+(text==null?"":text.replace("%","\\%").replace("_","\\_"))+"%";String sql="SELECT * FROM agent_memory WHERE user_id=? AND deleted=0 AND (project_id IS NULL OR project_id=?) AND (content LIKE ? ESCAPE '\\' OR structured_data LIKE ? ESCAPE '\\') AND (expires_at IS NULL OR expires_at>?) ORDER BY confirmed DESC,importance DESC,confidence DESC,updated_at DESC LIMIT ?";return query(sql,p->{p.setString(1,user);p.setString(2,project);p.setString(3,q);p.setString(4,q);p.setLong(5,System.currentTimeMillis());p.setInt(6,limit);});}
    @Override public boolean update(AgentMemoryEntity m,long old){try(Connection c=c();PreparedStatement p=c.prepareStatement("UPDATE agent_memory SET content=?,structured_data=?,importance=?,confidence=?,confirmed=?,source_session_id=?,source_event_id=?,updated_at=?,expires_at=?,deleted=? WHERE memory_id=? AND updated_at=?")){p.setString(1,m.getContent());p.setString(2,m.getStructuredData());p.setDouble(3,m.getImportance());p.setDouble(4,m.getConfidence());p.setInt(5,m.isConfirmed()?1:0);p.setString(6,m.getSourceSessionId());p.setString(7,m.getSourceEventId());p.setLong(8,m.getUpdatedAt());if(m.getExpiresAt()==null)p.setNull(9,Types.BIGINT);else p.setLong(9,m.getExpiresAt());p.setInt(10,m.isDeleted()?1:0);p.setString(11,m.getMemoryId());p.setLong(12,old);return p.executeUpdate()==1;}catch(SQLException e){throw new IllegalStateException(e);}}
    @Override public List<MemoryEvidenceEntity> findEvidence(String memoryId){List<MemoryEvidenceEntity> out=new ArrayList<>();try(Connection c=c();PreparedStatement p=c.prepareStatement("SELECT memory_id,evidence_type,evidence_id,created_at FROM agent_memory_evidence WHERE memory_id=? ORDER BY created_at")){p.setString(1,memoryId);try(ResultSet r=p.executeQuery()){while(r.next())out.add(MemoryEvidenceEntity.builder().memoryId(r.getString(1)).evidenceType(r.getString(2)).evidenceId(r.getString(3)).createdAt(r.getLong(4)).build());}}catch(SQLException e){throw new IllegalStateException(e);}return out;}
    @Override public void addEvidence(String memoryId,String type,String id,long at){try(Connection c=c()){evidence(c,memoryId,type,id,at);}catch(SQLException e){throw new IllegalStateException(e);}}
    private interface B{void x(PreparedStatement p)throws SQLException;}private List<AgentMemoryEntity> query(String sql,B b){List<AgentMemoryEntity> o=new ArrayList<>();try(Connection c=c();PreparedStatement p=c.prepareStatement(sql)){b.x(p);try(ResultSet r=p.executeQuery()){while(r.next())o.add(map(r));}}catch(SQLException e){throw new IllegalStateException(e);}return o;}
    private void bind(PreparedStatement p,AgentMemoryEntity m)throws SQLException{p.setString(1,m.getMemoryId());p.setString(2,m.getUserId());p.setString(3,m.getProjectId());p.setString(4,m.getMemoryType());p.setString(5,m.getContent());p.setString(6,m.getStructuredData());p.setDouble(7,m.getImportance());p.setDouble(8,m.getConfidence());p.setInt(9,m.isConfirmed()?1:0);p.setString(10,m.getSourceSessionId());p.setString(11,m.getSourceEventId());p.setLong(12,m.getCreatedAt());p.setLong(13,m.getUpdatedAt());if(m.getExpiresAt()==null)p.setNull(14,Types.BIGINT);else p.setLong(14,m.getExpiresAt());p.setInt(15,m.isDeleted()?1:0);}
    private void evidence(Connection c,String memoryId,String type,String id,long at)throws SQLException{try(PreparedStatement p=c.prepareStatement("INSERT OR IGNORE INTO agent_memory_evidence(memory_id,evidence_type,evidence_id,created_at) VALUES(?,?,?,?)")){p.setString(1,memoryId);p.setString(2,type);p.setString(3,id);p.setLong(4,at);p.executeUpdate();}}
    private AgentMemoryEntity map(ResultSet r)throws SQLException{long exp=r.getLong("expires_at");return AgentMemoryEntity.builder().memoryId(r.getString("memory_id")).userId(r.getString("user_id")).projectId(r.getString("project_id")).memoryType(r.getString("memory_type")).content(r.getString("content")).structuredData(r.getString("structured_data")).importance(r.getDouble("importance")).confidence(r.getDouble("confidence")).confirmed(r.getInt("confirmed")!=0).sourceSessionId(r.getString("source_session_id")).sourceEventId(r.getString("source_event_id")).createdAt(r.getLong("created_at")).updatedAt(r.getLong("updated_at")).expiresAt(r.wasNull()?null:exp).deleted(r.getInt("deleted")!=0).build();}
    private String ftsQuery(String text){String[] terms=text.trim().split("\\s+");StringBuilder out=new StringBuilder();for(String term:terms){String clean=term.replace("\"","\"\"");if(clean.isBlank())continue;if(out.length()>0)out.append(" OR ");out.append('"').append(clean).append('"');}return out.length()==0?"\"\"":out.toString();}
}
