package cn.bugstack.ai.infrastructure.persistence;

import cn.bugstack.ai.domain.eval.adapter.IAgentEvalRepository;
import com.alibaba.fastjson.JSON;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Repository;
import java.sql.*;
import java.util.*;

@Repository
public class JdbcAgentEvalRepository implements IAgentEvalRepository {
    private final JdbcTemplate jdbc;
    public JdbcAgentEvalRepository(JdbcTemplate jdbc){this.jdbc=jdbc;}

    @Override public List<Map<String,Object>> datasets(String user){return jdbc.query("select d.*,(select count(*) from eval_case c where c.dataset_id=d.id) case_count from eval_dataset d where owner_username=? order by updated_at desc",(r,n)->datasetMap(r),user);}
    @Override public Map<String,Object> dataset(String user,String id){List<Map<String,Object>> rows=jdbc.query("select d.*,(select count(*) from eval_case c where c.dataset_id=d.id) case_count from eval_dataset d where owner_username=? and id=?",(r,n)->datasetMap(r),user,uuid(id));return rows.isEmpty()?Map.of():rows.get(0);}
    @Override public String createDataset(String user,String key,String name,String description){UUID id=UUID.randomUUID();jdbc.update("insert into eval_dataset(id,owner_username,dataset_key,name,description) values (?,?,?,?,?)",id,user,key,name,Objects.toString(description,""));return id.toString();}
    @Override public List<Map<String,Object>> cases(String user,String datasetId,boolean enabled){return jdbc.query("select c.* from eval_case c join eval_dataset d on d.id=c.dataset_id where d.owner_username=? and c.dataset_id=?"+(enabled?" and c.enabled=true":"")+" order by c.created_at",(r,n)->caseMap(r),user,uuid(datasetId));}
    @Override public String createCase(String user,String datasetId,Map<String,Object>d){requireDataset(user,datasetId);UUID id=UUID.randomUUID();jdbc.update("insert into eval_case(id,dataset_id,case_key,name,agent_id,prompt,expectations,rubric,tags,enabled) values (?,?,?,?,?,?,cast(? as jsonb),cast(? as jsonb),cast(? as jsonb),?)",id,uuid(datasetId),required(d,"caseKey"),required(d,"name"),required(d,"agentId"),required(d,"prompt"),json(d.get("expectations"),"{}"),json(d.get("rubric"),"{}"),json(d.get("tags"),"[]"),!Boolean.FALSE.equals(d.get("enabled")));return id.toString();}
    @Override public void updateCase(String user,String id,Map<String,Object>d){List<Integer> owned=jdbc.query("select 1 from eval_case c join eval_dataset d on d.id=c.dataset_id where c.id=? and d.owner_username=?",(r,n)->1,uuid(id),user);if(owned.isEmpty())throw new SecurityException("Eval case access denied");jdbc.update("update eval_case set name=?,agent_id=?,prompt=?,expectations=cast(? as jsonb),rubric=cast(? as jsonb),tags=cast(? as jsonb),enabled=?,version=version+1,updated_at=now() where id=?",required(d,"name"),required(d,"agentId"),required(d,"prompt"),json(d.get("expectations"),"{}"),json(d.get("rubric"),"{}"),json(d.get("tags"),"[]"),!Boolean.FALSE.equals(d.get("enabled")),uuid(id));}
    @Override public String createRun(String user,String dataset,String label,int repeats,String baseline,int total){requireDataset(user,dataset);if(baseline!=null&&!baseline.isBlank()){List<Integer> valid=jdbc.query("select 1 from eval_run where id=? and dataset_id=? and owner_username=? and status='COMPLETED'",(r,n)->1,uuid(baseline),uuid(dataset),user);if(valid.isEmpty())throw new IllegalArgumentException("Baseline must be a completed run in the same dataset");}UUID id=UUID.randomUUID();jdbc.update("insert into eval_run(id,dataset_id,owner_username,candidate_label,status,repeat_count,baseline_run_id,total_cases) values (?,?,?,?,'QUEUED',?,?,?)",id,uuid(dataset),user,label,Math.max(1,repeats),uuid(baseline),total);return id.toString();}
    @Override public void startRun(String id){jdbc.update("update eval_run set status='RUNNING',started_at=now() where id=?",uuid(id));}
    @Override public String createCaseRun(String run,String caseId,long version,int repeat){UUID id=UUID.randomUUID();jdbc.update("insert into eval_case_run(id,eval_run_id,case_id,case_version,repeat_index,status) values (?,?,?,?,?,'QUEUED')",id,uuid(run),uuid(caseId),version,repeat);return id.toString();}
    @Override public void startCaseRun(String id,String session){jdbc.update("update eval_case_run set status='RUNNING',session_id=?,started_at=now() where id=?",session,uuid(id));}
    @Override public void completeCaseRun(String id,String invocation,String status,String output,double score,boolean passed,long duration,long input,long outputTokens,int tools,int models,Map<String,Object>breakdown,String error){jdbc.update("update eval_case_run set invocation_id=?,status=?,final_output=?,total_score=?,passed=?,duration_ms=?,input_tokens=?,output_tokens=?,tool_calls=?,model_calls=?,score_breakdown=cast(? as jsonb),error_message=?,completed_at=now() where id=?",invocation==null||invocation.isBlank()?null:invocation,status,output,score,passed,duration,input,outputTokens,tools,models,JSON.toJSONString(breakdown),error,uuid(id));}
    @Override public void addAssertion(String caseRun,Map<String,Object>a){jdbc.update("insert into eval_assertion_result(case_run_id,grader_type,assertion_key,description,passed,hard_gate,score,max_score,expected,actual,details) values (?,?,?,?,?,?,?,?,cast(? as jsonb),cast(? as jsonb),?)",uuid(caseRun),a.get("graderType"),a.get("key"),a.get("description"),a.get("passed"),a.get("hardGate"),a.get("score"),a.get("maxScore"),json(a.get("expected"),"{}"),json(a.get("actual"),"{}"),a.get("details"));}
    @Override public void finishRun(String id){jdbc.update("update eval_run r set status='COMPLETED',completed_at=now(),completed_cases=x.completed,passed_cases=x.passed,failed_cases=x.failed,average_score=x.score,average_duration_ms=x.duration,total_input_tokens=x.input,total_output_tokens=x.output,regression_count=x.regressions,gate_status=case when x.failed=0 and x.regressions=0 then 'PASSED' else 'FAILED' end,summary=jsonb_build_object('scoreDelta',x.score_delta,'baselineScore',x.baseline_score) from (select count(*) completed,count(*) filter(where cr.passed) passed,count(*) filter(where not cr.passed) failed,coalesce(avg(cr.total_score),0) score,coalesce(avg(cr.duration_ms),0)::bigint duration,coalesce(sum(cr.input_tokens),0) input,coalesce(sum(cr.output_tokens),0) output,count(*) filter(where b.total_score is not null and cr.total_score < b.total_score-1) regressions,coalesce(avg(cr.total_score)-avg(b.total_score),0) score_delta,coalesce(avg(b.total_score),0) baseline_score from eval_case_run cr join eval_run er on er.id=cr.eval_run_id left join eval_case_run b on b.eval_run_id=er.baseline_run_id and b.case_id=cr.case_id and b.repeat_index=cr.repeat_index where cr.eval_run_id=?) x where r.id=?",uuid(id),uuid(id));}
    @Override public void failRun(String id,String error){jdbc.update("update eval_run set status='FAILED',gate_status='ERROR',error_message=?,completed_at=now() where id=?",error,uuid(id));}
    @Override public void setBaseline(String user,String dataset,String run){jdbc.update("update eval_dataset set baseline_run_id=?,version=version+1,updated_at=now() where id=? and owner_username=? and exists(select 1 from eval_run r where r.id=? and r.dataset_id=eval_dataset.id and r.status='COMPLETED')",uuid(run),uuid(dataset),user,uuid(run));}
    @Override public List<Map<String,Object>> runs(String user,String dataset,int limit){int safe=Math.max(1,Math.min(limit,200));if(dataset==null||dataset.isBlank())return jdbc.query("select r.* from eval_run r where owner_username=? order by created_at desc limit ?",(r,n)->runMap(r),user,safe);return jdbc.query("select r.* from eval_run r where owner_username=? and dataset_id=? order by created_at desc limit ?",(r,n)->runMap(r),user,uuid(dataset),safe);}
    @Override public Map<String,Object> run(String user,String id){List<Map<String,Object>> rows=jdbc.query("select r.* from eval_run r where owner_username=? and id=?",(r,n)->runMap(r),user,uuid(id));return rows.isEmpty()?Map.of():rows.get(0);}
    @Override public List<Map<String,Object>> caseRuns(String user,String run){return jdbc.query("select cr.*,c.case_key,c.name case_name,c.agent_id from eval_case_run cr join eval_case c on c.id=cr.case_id join eval_run r on r.id=cr.eval_run_id where r.owner_username=? and cr.eval_run_id=? order by c.case_key,cr.repeat_index",(r,n)->caseRunMap(r),user,uuid(run));}
    @Override public List<Map<String,Object>> assertions(String user,String caseRun){return jdbc.query("select a.* from eval_assertion_result a join eval_case_run cr on cr.id=a.case_run_id join eval_run r on r.id=cr.eval_run_id where r.owner_username=? and a.case_run_id=? order by a.created_at",(r,n)->{Map<String,Object>m=new LinkedHashMap<>();m.put("id",r.getString("id"));m.put("graderType",r.getString("grader_type"));m.put("key",r.getString("assertion_key"));m.put("description",r.getString("description"));m.put("passed",r.getBoolean("passed"));m.put("hardGate",r.getBoolean("hard_gate"));m.put("score",r.getDouble("score"));m.put("maxScore",r.getDouble("max_score"));m.put("expected",parse(r.getString("expected")));m.put("actual",parse(r.getString("actual")));m.put("details",r.getString("details"));return m;},user,uuid(caseRun));}
    @Override public List<Map<String,Object>> evaluationsForInvocation(String user,String invocation){return jdbc.query("select cr.id case_run_id,cr.eval_run_id,cr.total_score,cr.passed,cr.status,c.name case_name,r.candidate_label from eval_case_run cr join eval_case c on c.id=cr.case_id join eval_run r on r.id=cr.eval_run_id where r.owner_username=? and cr.invocation_id=? order by r.created_at desc",(r,n)->Map.of("caseRunId",r.getString(1),"runId",r.getString(2),"score",r.getDouble(3),"passed",r.getBoolean(4),"status",r.getString(5),"caseName",r.getString(6),"candidateLabel",r.getString(7)),user,invocation);}

    private void requireDataset(String user,String id){if(dataset(user,id).isEmpty())throw new SecurityException("Eval dataset access denied");}
    private static Map<String,Object> datasetMap(ResultSet r)throws SQLException{Map<String,Object>m=new LinkedHashMap<>();m.put("id",r.getString("id"));m.put("key",r.getString("dataset_key"));m.put("name",r.getString("name"));m.put("description",r.getString("description"));m.put("version",r.getLong("version"));m.put("enabled",r.getBoolean("enabled"));m.put("baselineRunId",Objects.toString(r.getString("baseline_run_id"),""));m.put("caseCount",r.getInt("case_count"));m.put("createdAt",millis(r.getTimestamp("created_at")));m.put("updatedAt",millis(r.getTimestamp("updated_at")));return m;}
    private static Map<String,Object> caseMap(ResultSet r)throws SQLException{Map<String,Object>m=new LinkedHashMap<>();m.put("id",r.getString("id"));m.put("datasetId",r.getString("dataset_id"));m.put("caseKey",r.getString("case_key"));m.put("name",r.getString("name"));m.put("agentId",r.getString("agent_id"));m.put("prompt",r.getString("prompt"));m.put("expectations",parse(r.getString("expectations")));m.put("rubric",parse(r.getString("rubric")));m.put("tags",JSON.parseArray(r.getString("tags")));m.put("enabled",r.getBoolean("enabled"));m.put("version",r.getLong("version"));return m;}
    private static Map<String,Object> runMap(ResultSet r)throws SQLException{Map<String,Object>m=new LinkedHashMap<>();for(String c:new String[]{"id","dataset_id","candidate_label","status","baseline_run_id","gate_status","error_message"})m.put(camel(c),Objects.toString(r.getString(c),""));for(String c:new String[]{"repeat_count","total_cases","completed_cases","passed_cases","failed_cases","regression_count"})m.put(camel(c),r.getInt(c));m.put("averageScore",r.getDouble("average_score"));m.put("averageDurationMs",r.getLong("average_duration_ms"));m.put("totalInputTokens",r.getLong("total_input_tokens"));m.put("totalOutputTokens",r.getLong("total_output_tokens"));m.put("summary",parse(r.getString("summary")));m.put("createdAt",millis(r.getTimestamp("created_at")));m.put("startedAt",millis(r.getTimestamp("started_at")));m.put("completedAt",millis(r.getTimestamp("completed_at")));return m;}
    private static Map<String,Object> caseRunMap(ResultSet r)throws SQLException{Map<String,Object>m=new LinkedHashMap<>();for(String c:new String[]{"id","eval_run_id","case_id","invocation_id","session_id","status","case_key","case_name","agent_id","error_message"})m.put(camel(c),Objects.toString(r.getString(c),""));m.put("repeatIndex",r.getInt("repeat_index"));m.put("caseVersion",r.getLong("case_version"));m.put("finalOutput",r.getString("final_output"));m.put("totalScore",r.getDouble("total_score"));m.put("passed",r.getBoolean("passed"));m.put("durationMs",r.getLong("duration_ms"));m.put("inputTokens",r.getLong("input_tokens"));m.put("outputTokens",r.getLong("output_tokens"));m.put("toolCalls",r.getInt("tool_calls"));m.put("modelCalls",r.getInt("model_calls"));m.put("scoreBreakdown",parse(r.getString("score_breakdown")));return m;}
    private static String required(Map<String,Object>d,String k){String v=Objects.toString(d.get(k),"").trim();if(v.isEmpty())throw new IllegalArgumentException(k+" is required");return v;}
    private static String json(Object v,String fallback){return v==null?fallback:JSON.toJSONString(v);}
    @SuppressWarnings("unchecked") private static Map<String,Object> parse(String v){return v==null||v.isBlank()?Map.of():JSON.parseObject(v,Map.class);}
    private static UUID uuid(String v){try{return v==null||v.isBlank()?null:UUID.fromString(v);}catch(Exception e){return null;}}
    private static long millis(Timestamp t){return t==null?0:t.getTime();}
    private static String camel(String s){StringBuilder b=new StringBuilder();boolean up=false;for(char c:s.toCharArray()){if(c=='_'){up=true;continue;}b.append(up?Character.toUpperCase(c):c);up=false;}return b.toString();}
}
