package cn.bugstack.ai.infrastructure.persistence;

import cn.bugstack.ai.domain.artifact.adapter.IArtifactRepository;
import cn.bugstack.ai.domain.artifact.model.ArtifactView;
import cn.bugstack.ai.types.exception.AppException;
import com.alibaba.fastjson.JSON;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Repository;
import java.nio.charset.StandardCharsets;
import java.util.UUID;
import java.util.*;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.security.MessageDigest;
import java.util.HexFormat;
import org.springframework.transaction.support.TransactionTemplate;

@Repository
public class JdbcArtifactRepository implements IArtifactRepository {
    private final JdbcTemplate jdbc;private final TransactionTemplate tx;public JdbcArtifactRepository(JdbcTemplate jdbc,TransactionTemplate tx){this.jdbc=jdbc;this.tx=tx;}
    @Override public UUID save(UUID conversation,String invocation,String type,String name,String mime,String content,String metadata){return save(conversation,invocation,type,name,mime,content,metadata,null);}
    @Override public UUID save(UUID conversation,String invocation,String type,String name,String mime,String content,String metadata,String idempotencyKey){return tx.execute(status->{
        jdbc.queryForObject("select id from conversation where id=? for update",UUID.class,conversation);
        requireInvocationConversation(invocation,conversation);
        if(idempotencyKey!=null&&!idempotencyKey.isBlank()){List<UUID> existing=jdbc.query("select id from artifact where conversation_id=? and idempotency_key=?",(rs,n)->rs.getObject(1,UUID.class),conversation,idempotencyKey);if(!existing.isEmpty())return existing.get(0);}
        List<ArtifactView> previous=jdbc.query("select * from artifact where conversation_id=? and artifact_type=? and name=? and branch_name='main' order by version_no desc limit 1",this::map,conversation,type,name);ArtifactView parent=previous.isEmpty()?null:previous.get(0);UUID id=UUID.randomUUID(),lineage=parent==null?id:parent.lineageId();int version=parent==null?1:parent.versionNo()+1;
        Map<String,Object> enriched=metadata==null||metadata.isBlank()?new LinkedHashMap<>():new LinkedHashMap<>(JSON.parseObject(metadata,Map.class));if(invocation!=null){var capabilities=jdbc.queryForList("select capability_id,capability_version,schema_version,content_version,action,status from capability_execution where invocation_id=? order by started_at",invocation);enriched.put("capabilityProvenance",capabilities);}
        jdbc.update("insert into artifact(id,workspace_id,conversation_id,invocation_id,parent_artifact_id,lineage_id,branch_name,artifact_type,name,mime_type,storage_type,content_text,content_json,content_hash,size_bytes,version_no,idempotency_key,created_by) values (?,(select workspace_id from conversation where id=?),?,?,?,?,'main',?,?,?,'DATABASE',?,cast(? as jsonb),?,?,?,?,(select user_id from conversation where id=?))",id,conversation,conversation,invocation,parent==null?null:parent.id(),lineage,type,name,mime,content,JSON.toJSONString(enriched),hash(content),content==null?0:content.getBytes(StandardCharsets.UTF_8).length,version,idempotencyKey,conversation);return id;
    });}
    @Override public List<ArtifactView> list(String username,UUID conversation){ownedConversation(username,conversation);return jdbc.query("select * from artifact where conversation_id=? order by created_at desc",this::map,conversation);}
    @Override public ArtifactView get(String username,UUID id){return owned(username,id);}
    @Override public ArtifactView rollback(String username,UUID target,String invocation,String key){ArtifactView source=owned(username,target,true);UUID id=save(source.conversationId(),invocation,source.artifactType(),source.name(),source.mimeType(),source.content(),JSON.toJSONString(Map.of("operation","ROLLBACK","sourceArtifactId",target)),key);return get(username,id);}
    @Override public ArtifactView branch(String username,UUID target,String branch,String invocation,String key){ArtifactView source=owned(username,target,true);String safe=branch==null?"":branch.trim();if(!safe.matches("[a-zA-Z0-9._-]{1,120}"))throw new AppException("ARTIFACT_BRANCH_INVALID","分支名称仅支持字母、数字、点、下划线和短横线");return tx.execute(status->{jdbc.query("select pg_advisory_xact_lock(hashtext(?))",rs->null,source.lineageId()+":"+safe);requireInvocationConversation(invocation,source.conversationId());if(key!=null&&!key.isBlank()){var existing=jdbc.query("select * from artifact where conversation_id=? and idempotency_key=?",this::map,source.conversationId(),key);if(!existing.isEmpty())return existing.get(0);}UUID id=UUID.randomUUID();jdbc.update("insert into artifact(id,workspace_id,conversation_id,invocation_id,parent_artifact_id,lineage_id,branch_name,artifact_type,name,mime_type,storage_type,content_text,content_json,content_hash,size_bytes,version_no,idempotency_key,created_by) values (?,(select workspace_id from conversation where id=?),?,?,?,?,?,?,?,'DATABASE',?,cast(? as jsonb),?,?,1,?,(select user_id from conversation where id=?))",id,source.conversationId(),source.conversationId(),invocation,target,source.lineageId(),safe,source.artifactType(),source.name(),source.mimeType(),source.content(),JSON.toJSONString(Map.of("operation","BRANCH","sourceArtifactId",target)),source.contentHash(),source.sizeBytes(),key,source.conversationId());return get(username,id);});}
    @Override public String diff(String username,UUID baseId,UUID targetId){ArtifactView base=owned(username,baseId),target=owned(username,targetId);if(!base.lineageId().equals(target.lineageId()))throw new AppException("ARTIFACT_LINEAGE_MISMATCH","只能比较同一版本谱系的 Artifact");List<String>a=Arrays.asList(Objects.toString(base.content(),"").split("\\R",-1)),b=Arrays.asList(Objects.toString(target.content(),"").split("\\R",-1));StringBuilder out=new StringBuilder();int max=Math.max(a.size(),b.size());for(int i=0;i<max;i++){String left=i<a.size()?a.get(i):null,right=i<b.size()?b.get(i):null;if(Objects.equals(left,right))continue;if(left!=null)out.append("- ").append(left).append('\n');if(right!=null)out.append("+ ").append(right).append('\n');if(out.length()>20000){out.append("…[diff truncated]");break;}}return out.toString();}
    private ArtifactView owned(String username,UUID id){return owned(username,id,false);}
    private ArtifactView owned(String username,UUID id,boolean write){return jdbc.query("select a.* from artifact a join conversation c on c.id=a.conversation_id join workspace_member wm on wm.workspace_id=c.workspace_id join app_user u on u.id=wm.user_id where a.id=? and u.username=? and (?=false or wm.role in('OWNER','EDITOR'))",this::map,id,username,write).stream().findFirst().orElseThrow(()->new AppException("ARTIFACT_NOT_FOUND","Artifact 不存在或无权访问"));}
    private void ownedConversation(String username,UUID id){Integer count=jdbc.queryForObject("select count(*) from conversation c join workspace_member wm on wm.workspace_id=c.workspace_id join app_user u on u.id=wm.user_id where c.id=? and u.username=?",Integer.class,id,username);if(count==null||count==0)throw new AppException("CONVERSATION_ACCESS_DENIED","会话不存在或无权访问");}
    private void requireInvocationConversation(String invocation,UUID conversation){if(invocation==null||invocation.isBlank())return;Integer count=jdbc.queryForObject("select count(*) from agent_invocation where id=? and conversation_id=?",Integer.class,invocation,conversation);if(count==null||count!=1)throw new AppException("ARTIFACT_INVOCATION_MISMATCH","Invocation 不属于当前会话");}
    private ArtifactView map(ResultSet rs,int n)throws SQLException{return new ArtifactView(rs.getObject("id",UUID.class),rs.getObject("conversation_id",UUID.class),rs.getString("invocation_id"),rs.getObject("parent_artifact_id",UUID.class),rs.getObject("lineage_id",UUID.class),rs.getString("branch_name"),rs.getString("artifact_type"),rs.getString("name"),rs.getString("mime_type"),rs.getString("content_text"),rs.getString("content_hash"),rs.getLong("size_bytes"),rs.getInt("version_no"),rs.getString("status"),rs.getTimestamp("created_at").toInstant());}
    private String hash(String content){try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(Objects.toString(content,"").getBytes(StandardCharsets.UTF_8)));}catch(Exception e){throw new IllegalStateException(e);}}
}
