package cn.bugstack.ai.infrastructure.persistence;

import cn.bugstack.ai.domain.agent.adapter.repository.IDynamicSubagentRepository;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Repository;

import java.sql.Timestamp;
import java.util.*;

@Repository
public class JdbcDynamicSubagentRepository implements IDynamicSubagentRepository {
    private final JdbcTemplate jdbc;
    public JdbcDynamicSubagentRepository(JdbcTemplate jdbc){this.jdbc=jdbc;}

    @Override public List<Map<String,Object>> templates(){return jdbc.query("select template_key,display_name,description,max_steps,timeout_seconds,token_budget,permission_mode,version from agent_template where enabled=true order by template_key",(rs,n)->Map.of("templateKey",rs.getString(1),"displayName",rs.getString(2),"description",rs.getString(3),"maxSteps",rs.getInt(4),"timeoutSeconds",rs.getInt(5),"tokenBudget",rs.getLong(6),"permissionMode",rs.getString(7),"version",rs.getLong(8)));}
    @Override public Map<String,Object> template(String key){List<Map<String,Object>> rows=jdbc.query("select template_key,display_name,description,instruction,capability_groups::text,max_steps,timeout_seconds,token_budget,permission_mode,version from agent_template where template_key=? and enabled=true",(rs,n)->{Map<String,Object> m=new LinkedHashMap<>();m.put("templateKey",rs.getString(1));m.put("displayName",rs.getString(2));m.put("description",rs.getString(3));m.put("instruction",rs.getString(4));m.put("capabilityGroups",rs.getString(5));m.put("maxSteps",rs.getInt(6));m.put("timeoutSeconds",rs.getInt(7));m.put("tokenBudget",rs.getLong(8));m.put("permissionMode",rs.getString(9));m.put("version",rs.getLong(10));return m;},key);return rows.isEmpty()?Map.of():rows.get(0);}
    @Override public String createTask(String invocation,String parentRun,String template,String user,String text){UUID id=UUID.randomUUID();jdbc.update("insert into dynamic_subagent_task(id,parent_invocation_id,parent_run_id,template_key,requested_by,task_text,status) values (?,?,?,?,?,?,'PENDING')",id,invocation,uuid(parentRun),template,user,text);return id.toString();}
    @Override public String createTask(String invocation,String parentRun,String parentTask,int depth,List<String> dependencies,String template,String user,String text,long tokenBudget){UUID id=UUID.randomUUID();jdbc.update("insert into dynamic_subagent_task(id,parent_invocation_id,parent_run_id,parent_task_id,depth,dependencies,template_key,requested_by,task_text,status,token_budget) values (?,?,?,?,?,cast(? as jsonb),?,?,?,'PENDING',?)",id,invocation,uuid(parentRun),uuid(parentTask),depth,com.alibaba.fastjson.JSON.toJSONString(dependencies),template,user,text,tokenBudget);return id.toString();}
    @Override public void startTask(String id){jdbc.update("update dynamic_subagent_task set status='RUNNING',started_at=now(),version=version+1 where id=? and status='PENDING'",uuid(id));}
    @Override public void completeTask(String id,String childRun,String result){UUID run=uuid(childRun);jdbc.update("update dynamic_subagent_task set status='SUCCESS',child_run_id=?,result_text=?,completed_at=now(),duration_ms=extract(epoch from(now()-started_at))*1000,version=version+1 where id=?",run,result,uuid(id));markDynamic(run,id);}
    @Override public boolean completeTaskWithinBudget(String id,String childRun,String result){UUID run=uuid(childRun);int updated=0;if(run!=null)updated=jdbc.update("update dynamic_subagent_task t set child_run_id=?,result_text=?,input_tokens=coalesce(r.input_tokens,0),output_tokens=coalesce(r.output_tokens,0),status=case when coalesce(r.input_tokens,0)+coalesce(r.output_tokens,0)>t.token_budget then 'ERROR' else 'SUCCESS' end,error_message=case when coalesce(r.input_tokens,0)+coalesce(r.output_tokens,0)>t.token_budget then 'Token budget exceeded' else null end,completed_at=now(),duration_ms=extract(epoch from(now()-started_at))*1000,version=version+1 from agent_run r where t.id=? and r.id=? and t.status='RUNNING'",run,result,uuid(id),run);if(updated==0)jdbc.update("update dynamic_subagent_task set child_run_id=?,result_text=?,status='SUCCESS',error_message=null,completed_at=now(),duration_ms=extract(epoch from(now()-started_at))*1000,version=version+1 where id=? and status='RUNNING'",run,result,uuid(id));markDynamic(run,id);return Boolean.TRUE.equals(jdbc.queryForObject("select status='SUCCESS' from dynamic_subagent_task where id=?",Boolean.class,uuid(id)));}
    @Override public void failTask(String id,String childRun,String error){UUID run=uuid(childRun);jdbc.update("update dynamic_subagent_task set status='ERROR',child_run_id=?,error_message=?,completed_at=now(),duration_ms=extract(epoch from(now()-started_at))*1000,version=version+1 where id=? and status in('PENDING','RUNNING')",run,error,uuid(id));markDynamic(run,id);}
    @Override public void failTask(String id,String childRun,String error,String partialResult){UUID run=uuid(childRun);jdbc.update("update dynamic_subagent_task set status='ERROR',child_run_id=?,error_message=?,result_text=?,completed_at=now(),duration_ms=extract(epoch from(now()-started_at))*1000,version=version+1 where id=? and status in('PENDING','RUNNING')",run,error,partialResult,uuid(id));markDynamic(run,id);}
    @Override public List<Map<String,Object>> tasks(String username,String invocation){return jdbc.query("select t.* from dynamic_subagent_task t join agent_invocation i on i.id=t.parent_invocation_id join conversation c on c.adk_session_id=i.adk_session_id join app_user u on u.id=c.user_id where u.username=? and t.parent_invocation_id=? order by t.created_at",(rs,n)->{Map<String,Object> m=new LinkedHashMap<>();m.put("taskId",rs.getString("id"));m.put("parentTaskId",Objects.toString(rs.getString("parent_task_id"),""));m.put("parentRunId",Objects.toString(rs.getString("parent_run_id"),""));m.put("childRunId",Objects.toString(rs.getString("child_run_id"),""));m.put("depth",rs.getInt("depth"));m.put("dependencies",rs.getString("dependencies"));m.put("templateKey",rs.getString("template_key"));m.put("task",rs.getString("task_text"));m.put("status",rs.getString("status"));m.put("result",rs.getString("result_text"));m.put("error",rs.getString("error_message"));m.put("tokenBudget",rs.getLong("token_budget"));m.put("inputTokens",rs.getLong("input_tokens"));m.put("outputTokens",rs.getLong("output_tokens"));m.put("createdAt",millis(rs.getTimestamp("created_at")));m.put("startedAt",millis(rs.getTimestamp("started_at")));m.put("completedAt",millis(rs.getTimestamp("completed_at")));m.put("durationMs",rs.getLong("duration_ms"));return m;},username,invocation);}
    private static UUID uuid(String value){try{return value==null||value.isBlank()?null:UUID.fromString(value);}catch(Exception ignored){return null;}}
    private void markDynamic(UUID run,String taskId){if(run!=null)jdbc.update("update agent_run r set run_kind='DYNAMIC',template_key=t.template_key from dynamic_subagent_task t where r.id=? and t.id=?",run,uuid(taskId));}
    private static long millis(Timestamp value){return value==null?0:value.getTime();}
}
