import { useQuery } from '@tanstack/react-query';
import { useState } from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import { queryInvocation, queryInvocations, queryMonitorSummary, querySessionInvocations, queryWorkflowDetail } from '../features/monitor/monitor.api';
import { queryConversations } from '../features/history/history.api';
import { WaterfallTrace } from '../features/monitor/WaterfallTrace';
import { CapabilityTrace } from '../features/monitor/CapabilityTrace';
import type { InvocationItem } from '../features/monitor/monitor.types';

const duration = (ms: number) => ms < 1000 ? `${ms} ms` : `${(ms / 1000).toFixed(1)} s`;
const time = (value: number) => value ? new Date(value).toLocaleTimeString('zh-CN') : '运行中';

export function MonitorPage() {
  const [searchParams] = useSearchParams();
  const [selected, setSelected] = useState(() => searchParams.get('invocation') ?? '');
  const [sessionFilter, setSessionFilter] = useState('');
  const [invocationCollapsed, setInvocationCollapsed] = useState(false);
  const options = { refetchInterval: 2000 } as const;
  const summary = useQuery({ queryKey: ['monitor-summary', sessionFilter], queryFn: () => queryMonitorSummary(sessionFilter || undefined), ...options });
  const invocations = useQuery({ queryKey: ['monitor-invocations'], queryFn: queryInvocations, ...options });
  const conversations = useQuery({ queryKey: ['monitor-conversations'], queryFn: queryConversations });
  const sessionInvocations = useQuery({ queryKey: ['monitor-session', sessionFilter], queryFn: () => querySessionInvocations(sessionFilter), enabled: !!sessionFilter, ...options });
  const invocationItems = sessionFilter ? sessionInvocations.data : invocations.data;
  const workflowGroups = Object.entries((invocationItems ?? []).reduce<Record<string, InvocationItem[]>>((groups, item) => {
    const key = item.taskId || item.invocationId;
    (groups[key] ??= []).push(item);
    return groups;
  }, {}));
  const detail = useQuery({ queryKey: ['monitor-invocation', selected], queryFn: () => queryInvocation(selected), enabled: !!selected, ...options });
  const workflow = useQuery({ queryKey:['monitor-workflow',detail.data?.task?.id],queryFn:()=>queryWorkflowDetail(detail.data!.task!.id),enabled:!!detail.data?.task?.id,...options });
  const stats = summary.data;
  return <main className="monitor-page">
    <header className="monitor-header"><div><p className="eyebrow">OBSERVABILITY</p><h1>Agent 运行观测台</h1><p>PostgreSQL 持久化链路 · {sessionFilter ? `Session ${sessionFilter}` : '全部 Session'} · 每 2 秒刷新</p></div><nav><select value={sessionFilter} onChange={(event)=>{setSessionFilter(event.target.value);setSelected('')}}><option value="">全部 Session</option>{conversations.data?.map(item=><option value={item.sessionId} key={item.id}>{item.sessionId}</option>)}</select><Link className="button" to="/eval">Agent Eval</Link><Link className="button" to="/workspace">返回工作台</Link></nav></header>
    <section className="metric-grid">
      <article><span>总调用</span><strong>{stats?.total ?? '—'}</strong></article><article><span>运行中</span><strong>{stats?.active ?? '—'}</strong></article><article><span>成功 / 异常</span><strong>{stats ? `${stats.success} / ${stats.errors}` : '—'}</strong></article><article><span>平均耗时</span><strong>{stats ? duration(stats.averageDurationMs) : '—'}</strong></article><article><span>输入 Tokens</span><strong>{stats?.inputTokens.toLocaleString() ?? '—'}</strong></article><article><span>输出 Tokens</span><strong>{stats?.outputTokens.toLocaleString() ?? '—'}</strong></article>
    </section>
    <div className={`monitor-layout ${invocationCollapsed ? 'invocation-collapsed' : ''}`}>
      <section className="invocation-list"><div className="invocation-heading"><h2>{invocationCollapsed ? '调用' : 'Workflow / Invocation'}</h2><button className="invocation-toggle" title={invocationCollapsed ? '展开 Invocation' : '收起 Invocation'} onClick={() => setInvocationCollapsed(value => !value)}>{invocationCollapsed ? '›' : '‹'}</button></div><div className="invocation-items">{workflowGroups.map(([taskId, items]) => <div className="workflow-invocation-group" key={taskId}><div className="workflow-invocation-title"><b>{items[0]?.workflowName || '未知 Agent'}</b><small>{items.length} Invocation</small></div>{items.map(item => <button key={item.invocationId} className={selected === item.invocationId ? 'active' : ''} onClick={() => setSelected(item.invocationId)}><span><b>{item.rootAgent}</b><i className={`monitor-status ${item.status.toLowerCase()}`}>{item.status}</i></span><small>{item.invocationId.slice(0, 13)} · {duration(item.durationMs)}</small><small>{item.agentCount} Agent · {item.toolCount} Tool · {item.eventCount} Event</small></button>)}</div>)}{!invocationItems?.length && <p className="monitor-empty">当前范围内暂无 Agent 调用记录。</p>}</div></section>
      <section className="trace-detail"><h2>调用链路</h2>{!selected && <p className="monitor-empty">选择左侧 Invocation 查看生命周期详情。</p>}{selected && detail.isLoading && <p className="monitor-empty">正在加载 Invocation 详情…</p>}{detail.error && <div className="monitor-detail-error"><strong>详情加载失败</strong><p>{detail.error.message}</p><button className="button tiny" onClick={() => void detail.refetch()}>重试</button></div>}{detail.data && <>
        <div className="trace-meta"><span>开始 {time(detail.data.startedAt)}</span><span>耗时 {duration(detail.data.durationMs)}</span><span>Session {detail.data.sessionId.slice(0, 12)}</span><span>Tokens {detail.data.tokensEstimated ? '≈ ' : ''}{detail.data.inputTokens.toLocaleString()} 输入 / {detail.data.outputTokens.toLocaleString()} 输出</span></div>
        {workflow.data && <><h3>Workflow 汇总</h3><div className="metric-grid workflow-metrics"><article><span>业务总耗时</span><strong>{duration(workflow.data.wallDurationMs)}</strong></article><article><span>实际执行</span><strong>{duration(workflow.data.computeDurationMs)}</strong></article><article><span>人工等待</span><strong>{duration(workflow.data.userWaitDurationMs)}</strong></article><article><span>队列等待</span><strong>{duration(workflow.data.queueWaitDurationMs)}</strong></article><article><span>模型 / Tool</span><strong>{duration(workflow.data.modelDurationMs)} / {duration(workflow.data.toolDurationMs)}</strong></article><article><span>Invocation</span><strong>{workflow.data.invocations.length}</strong></article><article><span>Tokens</span><strong>{(workflow.data.inputTokens+workflow.data.outputTokens).toLocaleString()}</strong></article><article><span>估算费用</span><strong>{Number(workflow.data.estimatedCost||0)>0?`$${Number(workflow.data.estimatedCost).toFixed(6)}`:'未配置单价'}</strong></article><article><span>Tool 成功 / 重试</span><strong>{workflow.data.toolStats.success}/{workflow.data.toolStats.total} · {workflow.data.toolStats.retries}</strong></article><article><span>Artifact</span><strong>{workflow.data.artifactCount}</strong></article></div>{workflow.data.artifacts?.length>0&&<div className="monitor-card-list"><h4>Artifact 版本</h4>{workflow.data.artifacts.map(item=><article key={item.id}><strong>{item.name} · {item.branch_name}/v{item.version_no}</strong><small>{item.artifact_type} · {(item.size_bytes||0).toLocaleString()} bytes · {item.invocation_id?.slice(0,13)}</small></article>)}</div>}<div className="timeline workflow-transitions">{workflow.data.transitions.map(item=><article key={item.sequence_no}><span className="timeline-dot"/><div><strong>{item.from_status||'START'} → {item.to_status}</strong><p>{item.invocation_id?`Invocation ${item.invocation_id.slice(0,13)}`:'Workflow 状态变更'} · {new Date(item.occurred_at).toLocaleTimeString('zh-CN')}</p></div></article>)}</div></>}
        {detail.data.evaluations?.length ? <div className="eval-trace-links"><strong>Eval 关联</strong>{detail.data.evaluations.map(item=><Link key={item.caseRunId} to={`/eval?run=${encodeURIComponent(item.runId)}`}>{item.candidateLabel} · {item.caseName} · {item.score.toFixed(1)} 分 · {item.passed?'PASS':'FAIL'}</Link>)}</div> : null}
        {detail.data.task && <div className="compression-card"><strong>{detail.data.task.title}</strong><span>{detail.data.task.taskType} · Revision {detail.data.task.version}</span><i className={`monitor-status ${detail.data.task.status.toLowerCase()}`}>{detail.data.task.status}</i></div>}
        <h3>统一调用瀑布</h3><WaterfallTrace items={detail.data.waterfall ?? []}/>
        <h3>动态 Subagent 任务</h3>{detail.data.subagentTasks?.length ? <div className="tool-table">{detail.data.subagentTasks.map(task=><article key={task.taskId}><strong>{task.templateKey}</strong><span>{task.task}</span><span>{duration(task.durationMs)}</span><i className={`monitor-status ${task.status.toLowerCase()}`}>{task.status}</i>{task.result && <small>结果：{task.result}</small>}{task.error && <small className="tool-error">错误：{task.error}</small>}</article>)}</div> : <p className="monitor-empty compact">本次没有动态创建 Subagent。</p>}
        <h3>Subagent 运行记录</h3>{detail.data.agentRuns?.length ? <div className="tool-table">{detail.data.agentRuns.map(run=><article key={run.runId} style={{marginLeft:run.role === 'SUBAGENT' ? 18 : 0}}><strong>{run.agentName}</strong><span>{run.role === 'ROOT' ? '根 Agent · 含全部子运行汇总' : `Subagent · 父运行 ${run.parentRunId.slice(0,8) || '未识别'}`}</span><span>{duration(run.durationMs)} · 模型 {run.modelCallCount} · Tool {run.toolCallCount}</span><i className={`monitor-status ${run.status.toLowerCase()}`}>{run.status}</i><small>{run.inputTokens.toLocaleString()} 输入 / {run.outputTokens.toLocaleString()} 输出{run.retryCount ? ` · 重试 ${run.retryCount}` : ''}</small>{run.error && <small className="tool-error">{run.error}</small>}</article>)}</div> : <p className="monitor-empty compact">当前 Invocation 暂无 Agent 运行记录。</p>}
        <h3>执行步骤</h3>{detail.data.steps?.length ? <div className="timeline">{detail.data.steps.map(step=><article key={step.id}><span className="timeline-dot"/><div><strong>#{step.sequenceNo} {step.stepType} · {step.stepName}</strong><p>{step.agentName || '工作流'} · {duration(step.durationMs)} · {step.status}{step.retryCount ? ` · 重试 ${step.retryCount} 次` : ''}</p>{step.error && <small className="tool-error">{step.error}</small>}</div></article>)}</div> : <p className="monitor-empty compact">当前 Invocation 暂无持久化步骤。</p>}
        <h3>Agent 生命周期</h3><div className="timeline">{detail.data.agents.sort((a,b)=>a.startedAt-b.startedAt).map(agent => <article key={agent.name}><span className="timeline-dot"/><div><strong>{agent.name}</strong><p>总耗时 {duration(agent.durationMs)} · {agent.modelCalls ? `模型 ${agent.modelCalls} 次 / ${duration(agent.modelDurationMs)} · ${agent.totalTokens.toLocaleString()} tokens` : '编排 Agent（不直接调用模型）'}</p></div></article>)}</div>
        <h3>模型调用</h3>{detail.data.models?.length ? <div className="tool-table model-call-table">{detail.data.models.map(model=><article key={model.id}><strong>{model.modelName}</strong><span>{model.agentName}</span><span>{duration(model.durationMs)}</span><i className={`monitor-status ${model.status.toLowerCase()}`}>{model.status}</i><small>{model.inputTokens.toLocaleString()} 输入 / {model.outputTokens.toLocaleString()} 输出{model.error ? ` · ${model.error}` : ''}</small></article>)}</div> : <p className="monitor-empty compact">本次未记录模型调用。</p>}
        <h3>模型路由</h3>{detail.data.modelDecisions?.length ? <div className="tool-table">{detail.data.modelDecisions.map((item,index) => <article key={`${item.timestamp}-${index}`}><strong>{item.model || 'Agent 默认模型'}</strong><span>{item.agentName}</span><span>{item.explicit ? '用户指定' : `复杂度 L${item.complexity}`}</span><i>{item.reason}</i></article>)}</div> : <p className="monitor-empty compact">本次未记录模型路由决策。</p>}
        <h3>能力决策链</h3><CapabilityTrace searches={detail.data.capabilitySearches??[]} executions={detail.data.capabilityExecutions??[]}/>
        <h3>Tools / MCP / Skills</h3><p className="registered-tools">入口工具：{stats?.registeredTools.length ? stats.registeredTools.join('、') : '无'} · 注册表能力 {stats?.registeredCapabilities ?? 0} 项</p>{detail.data.tools.length ? <div className="tool-table">{detail.data.tools.map(tool => <article key={tool.callId}><strong>{tool.toolName}</strong><span>{tool.agentName || 'Agent'}</span><span>{duration(tool.durationMs)} · {tool.attempts?.length ?? 1} 次尝试</span><i className={`monitor-status ${tool.status.toLowerCase()}`}>{tool.status}</i>{tool.arguments && <small>参数：{tool.arguments}</small>}{tool.summary && <small>结果：{tool.summary}</small>}{tool.error && <small className="tool-error">错误：{tool.error}</small>}</article>)}</div> : <p className="monitor-empty compact">工具已可用，但本次模型没有实际调用。</p>}
        <h3>上下文压缩</h3>{detail.data.compressions.length ? detail.data.compressions.map((item,index)=><div className="compression-card" key={`${item.timestamp}-${index}`}><strong>{item.strategy}</strong><span>{item.beforeTokens.toLocaleString()} → {item.afterTokens.toLocaleString()} tokens</span><span>{duration(item.durationMs)}</span></div>) : <p className="monitor-empty compact">本次未触发上下文压缩。</p>}
      </>}</section>
    </div>
  </main>;
}
